Repository polaris-hub/polaris, pull requests merged in 2024-12, with the labels that each got.

#227 Fix: Optimize PDB adapter
  polaris/dataset/converters/_pdb.py
  polaris/dataset/converters/_sdf.py
  polaris/dataset/converters/_zarr.py
  polaris/dataset/zarr/_utils.py
  polaris/experimental/_dataset_v2.py
Labels: fix

#228 Testing: Added Windows to CICD testing matrix, add hub integration test and fix errors
  .github/workflows/code-check.yml
  .github/workflows/doc.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  polaris/__init__.py
  polaris/dataset/zarr/_memmap.py
  polaris/hub/client.py
  polaris/hub/storage.py
  polaris/loader/__init__.py
  polaris/loader/load.py
  tests/test_hub_integration.py
  tests/test_zarr_checksum.py
Labels: test

#225 feat: Support result upload for XL benchmarks
  polaris/benchmark/_base.py
  polaris/dataset/_base.py
  polaris/evaluate/__init__.py
  polaris/evaluate/_results.py
  polaris/evaluate/utils.py
  polaris/hub/client.py
Labels: enhancement, feature

#229 chore: Optimize Zarr store copy operation to Hub storage
  polaris/dataset/_base.py
  polaris/dataset/_dataset.py
  polaris/experimental/_dataset_v2.py
  polaris/hub/client.py
  polaris/hub/storage.py
  tests/test_dataset.py
Labels: enhancement, feature

#223 Feature: Add the ability to compute metrics per group and then aggregate
  docs/tutorials/custom_dataset_benchmark.ipynb
  polaris/benchmark/_base.py
  polaris/dataset/_subset.py
  polaris/evaluate/_metric.py
  polaris/evaluate/_predictions.py
  polaris/evaluate/_results.py
  polaris/evaluate/metrics/__init__.py
  polaris/evaluate/metrics/generic_metrics.py
  polaris/evaluate/utils.py
  polaris/hub/settings.py
  polaris/utils/types.py
  tests/conftest.py
  tests/test_benchmark.py
  tests/test_benchmark_predictions.py
  tests/test_competition.py
  tests/test_evaluate.py
  tests/test_metrics.py
Labels: feature

#233 Fix: Add alias for `custom_name` in `Metric`
  polaris/benchmark/_base.py
  polaris/evaluate/_metric.py
  tests/test_benchmark.py
Labels: fix

#234 feat: Support for handling Benchmarks V2
  env.yml
  polaris/_artifact.py
  polaris/benchmark/__init__.py
  polaris/benchmark/_base.py
  polaris/benchmark/_definitions.py
  polaris/competition/_competition.py
  polaris/dataset/_dataset.py
  polaris/dataset/_subset.py
  polaris/evaluate/_metric.py
  polaris/experimental/_benchmark_v2.py
  polaris/experimental/_dataset_v2.py
  polaris/hub/client.py
  polaris/hub/oauth.py
  polaris/hub/storage.py
  polaris/loader/load.py
  polaris/utils/types.py
  pyproject.toml
  test.roaring
  tests/test_benchmark.py
  tests/test_benchmark_v2.py
  tests/test_integration.py
  tests/test_metrics.py
  training.roaring
Labels: feature

#230 Misc changes
  polaris/hub/client.py
  tests/conftest.py
  tests/test_benchmark.py
  tests/test_dataset.py
  tests/test_dataset_v2.py
  tests/test_evaluate.py
  tests/test_factory.py
  tests/test_zarr_checksum.py
Labels: fix
