Repository polaris-hub/polaris, pull requests merged in 2024-09, with the labels that each got.

#185 Adding new Zarr manifest generation to DatasetV2 class
  polaris/dataset/__init__.py
  polaris/dataset/_base.py
  polaris/dataset/_dataset.py
  polaris/experimental/_dataset_v2.py
  polaris/utils/v2_manifest.py
  tests/test_dataset_v2.py
Labels: feature

#194 add timeout argument
  polaris/dataset/_dataset.py
Labels: fix

#193 Chore: Add catch-all 'other' category to the generated changelog
  .github/changelog_config.json
Labels: chore

#186 XL Datasets: Minimal Zarr-only dataset implementation
  docs/api/dataset.md
  docs/quickstart.md
  polaris/benchmark/_base.py
  polaris/dataset/__init__.py
  polaris/dataset/_base.py
  polaris/dataset/_column.py
  polaris/dataset/_competition_dataset.py
  polaris/dataset/_dataset.py
  polaris/dataset/_factory.py
  polaris/dataset/_subset.py
  polaris/dataset/converters/_pdb.py
  polaris/dataset/converters/_sdf.py
  polaris/dataset/zarr/__init__.py
  polaris/dataset/zarr/_checksum.py
  polaris/dataset/zarr/_manifest.py
  polaris/experimental/__init__.py
  polaris/experimental/_dataset_v2.py
  polaris/hub/client.py
  polaris/loader/load.py
  polaris/utils/errors.py
  polaris/utils/misc.py
  polaris/utils/types.py
  tests/conftest.py
  tests/test_dataset.py
  tests/test_dataset_v2.py
  tests/test_evaluate.py
Labels: feature

#198 Type the return type of `@model_validator(mode="after")` with `Self`
  polaris/benchmark/_base.py
  polaris/dataset/_base.py
  polaris/dataset/_competition_dataset.py
  polaris/dataset/_dataset.py
  polaris/experimental/_dataset_v2.py
Labels: chore

#199 Add ligand RMSD metrics
  docs/api/evaluation.md
  polaris/evaluate/_metric.py
  polaris/evaluate/metrics/__init__.py
  polaris/evaluate/metrics/docking_metrics.py
  polaris/evaluate/metrics/generic_metrics.py
  polaris/evaluate/utils.py
  polaris/utils/types.py
  tests/conftest.py
  tests/test_evaluate.py
Labels: feature

#200 feat: Bucket operations using storage token
  .gitignore
  docs/api/hub.external_client.md
  docs/api/hub.storage.md
  env.yml
  mkdocs.yml
  polaris/_artifact.py
  polaris/benchmark/_base.py
  polaris/competition/_competition.py
  polaris/dataset/__init__.py
  polaris/dataset/_base.py
  polaris/dataset/_competition_dataset.py
  polaris/dataset/_dataset.py
  polaris/dataset/_factory.py
  polaris/evaluate/_results.py
  polaris/experimental/_dataset_v2.py
  polaris/hub/client.py
  polaris/hub/external_client.py
  polaris/hub/oauth.py
  polaris/hub/polarisfs.py
  polaris/hub/storage.py
  polaris/loader/load.py
  polaris/utils/errors.py
  polaris/utils/misc.py
  polaris/utils/types.py
  pyproject.toml
  tests/test_dataset.py
  tests/test_dataset_v2.py
  tests/test_factory.py
  tests/test_storage.py
Labels: feature

#205 Fix/minor fix
  polaris/benchmark/_base.py
  polaris/evaluate/metrics/docking_metrics.py
  polaris/evaluate/utils.py
Labels: fix
