Repository polaris-hub/polaris, pull requests merged in 2024-10, with the labels that each got.

#191 XL Datasets: Upload
  polaris/dataset/__init__.py
  polaris/dataset/_base.py
  polaris/dataset/_column.py
  polaris/dataset/_dataset.py
  polaris/dataset/_subset.py
  polaris/dataset/zarr/_manifest.py
  polaris/experimental/_dataset_v2.py
  polaris/hub/client.py
  polaris/hub/oauth.py
  polaris/hub/storage.py
  tests/conftest.py
  tests/test_evaluate.py
Labels: feature

#208 chore: Update dataset manifest build
  polaris/dataset/zarr/_manifest.py
Labels: chore

#210 Feature: Download for V2 datasets
  polaris/dataset/_base.py
  polaris/dataset/_dataset.py
  polaris/experimental/_dataset_v2.py
  polaris/hub/client.py
  polaris/hub/external_client.py
  polaris/hub/storage.py
Labels: feature

#211 Chore: Update README to include recent publication
  README.md
Labels: chore

#213 Fix: Exclude some computed properties during caching
  polaris/experimental/_dataset_v2.py
Labels: fix
