Repository polaris-hub/polaris, pull requests merged in 2024-05, with the labels that each got.

#96 Optimize the data loader for datasets that fit in memory or on a local disk
  docs/tutorials/custom_dataset_benchmark.ipynb
  docs/tutorials/optimization.ipynb
  mkdocs.yml
  polaris/dataset/_dataset.py
  polaris/dataset/_subset.py
  polaris/dataset/converters/_sdf.py
  polaris/dataset/zarr/__init__.py
  polaris/dataset/zarr/_memmap.py
  tests/test_dataset.py
Labels: feature

#103 Competition evaluation
  polaris/benchmark/_base.py
  polaris/competition/_competition.py
  polaris/evaluate/utils.py
  polaris/hub/client.py
  polaris/utils/context.py
  polaris/utils/types.py
  tests/conftest.py
  tests/test_competition.py
  tests/test_evaluate.py
Labels: feature

#107 Fix `UserWarning` during serialization and `DeprecationWarning`
  polaris/benchmark/_base.py
  polaris/benchmark/_definitions.py
  polaris/hub/settings.py
  polaris/utils/types.py
  tests/test_type_checks.py
Labels: fix

#106 feat: Update settings for production environment
  polaris/hub/settings.py
Labels: enhancement, feature

#108 fix: Client ignoring default .env file
  .github/workflows/code-check.yml
  polaris/benchmark/_base.py
  polaris/cli.py
  polaris/evaluate/_results.py
  polaris/hub/client.py
Labels: fix

#109 Use evaluation logic directly in hub, no need for wrapper
  polaris/competition/_competition.py
  polaris/evaluate/__init__.py
  polaris/hub/client.py
  tests/test_competition.py
Labels: feature
