Repository polaris-hub/polaris, pull requests merged in 2024-03, with the labels that each got.

#71 Easily featurize the inputs in the `Subset` class
  docs/tutorials/basics.ipynb
  polaris/benchmark/_base.py
  polaris/dataset/_subset.py
  polaris/utils/types.py
  pyproject.toml
  tests/conftest.py
  tests/test_integration.py
  tests/test_subset.py
Labels: feature, test

#73 feature: polaris fsspec write implementation
  polaris/hub/client.py
  polaris/hub/polarisfs.py
  polaris/hub/settings.py
  polaris/utils/types.py
Labels: feature

#78 Fix default settings for the `PolarisHubSettings`
  polaris/hub/settings.py
Labels: fix

#77 Add additional features to support SDF to Zarr conversion
  docs/api/adapters.md
  docs/api/converters.md
  docs/api/factory.md
  docs/tutorials/basics.ipynb
  docs/tutorials/custom_dataset_benchmark.ipynb
  docs/tutorials/data_curation.ipynb
  docs/tutorials/dataset_factory.ipynb
  docs/tutorials/dataset_zarr.ipynb
  mkdocs.yml
  polaris/benchmark/_base.py
  polaris/dataset/__init__.py
  polaris/dataset/_adapters.py
  polaris/dataset/_dataset.py
  polaris/dataset/_factory.py
  polaris/dataset/_subset.py
  polaris/dataset/converters/__init__.py
  polaris/dataset/converters/_base.py
  polaris/dataset/converters/_sdf.py
  polaris/dataset/converters/_zarr.py
  polaris/loader/load.py
  polaris/utils/types.py
  tests/conftest.py
  tests/test_dataset.py
  tests/test_factory.py
  tests/test_integration.py
  tests/test_subset.py
Labels: feature

#80 Hotfix: Added option to disable the checksum verification
  polaris/hub/client.py
  polaris/loader/load.py
Labels: fix

#81 Changed the community references in the docs from Portal to Discord
  docs/index.md
  mkdocs.yml
Labels: documentation

#83 Add a flow to use Zarr datasets through the Hub
  docs/tutorials/dataset_factory.ipynb
  docs/tutorials/dataset_zarr.ipynb
  polaris/benchmark/_base.py
  polaris/dataset/_dataset.py
  polaris/dataset/_factory.py
  polaris/dataset/converters/_base.py
  polaris/dataset/converters/_sdf.py
  polaris/dataset/converters/_zarr.py
  polaris/hub/client.py
  polaris/hub/polarisfs.py
  polaris/loader/load.py
  polaris/utils/fs.py
  polaris/utils/io.py
  tests/conftest.py
  tests/test_dataset.py
Labels: feature

#84 Added the version attribute to the artifact data model
  polaris/_artifact.py
  tests/conftest.py
  tests/test_evaluate.py
  tests/test_type_checks.py
Labels: feature

#82 feat: consolidating metadata for opening zarr files in read mode
  polaris/dataset/_dataset.py
  polaris/dataset/_factory.py
  polaris/hub/client.py
  tests/conftest.py
  tests/test_dataset.py
Labels: enhancement

#85 Fix a bug in Dataset.cache() and set a default timeout for the PolarisHubClient
  polaris/dataset/_dataset.py
  polaris/hub/client.py
Labels: fix
