Repository polaris-hub/polaris, pull requests merged in 2024-07, with the labels that each got.

#122 feat: JWT-based authentication for Hub API requests
  docs/api/hub.external_auth_client.md
  docs/tutorials/custom_dataset_benchmark.ipynb
  polaris/evaluate/_results.py
  polaris/hub/client.py
  polaris/hub/external_auth_client.py
  polaris/hub/oauth.py
  polaris/hub/settings.py
  polaris/utils/constants.py
  polaris/utils/types.py
  pyproject.toml
  tests/test_oauth.py
Labels: enhancement

#129 fix: Errors in login and owner parsing
  polaris/hub/client.py
  polaris/hub/external_auth_client.py
Labels: fix

#130 Fix auth token being `None` during login
  polaris/hub/client.py
Labels: fix

#102 Include a checksum for Zarr archives in the Dataset checksum
  LICENSE
  NOTICE
  docs/api/dataset.md
  polaris/__init__.py
  polaris/_mixins.py
  polaris/benchmark/_base.py
  polaris/dataset/_adapters.py
  polaris/dataset/_dataset.py
  polaris/dataset/_subset.py
  polaris/dataset/converters/_zarr.py
  polaris/dataset/zarr/__init__.py
  polaris/dataset/zarr/_checksum.py
  polaris/dataset/zarr/_memmap.py
  polaris/hub/client.py
  polaris/hub/polarisfs.py
  polaris/hub/settings.py
  polaris/loader/load.py
  polaris/utils/errors.py
  polaris/utils/httpx.py
  polaris/utils/misc.py
  polaris/utils/types.py
  pyproject.toml
  tests/conftest.py
  tests/test_benchmark.py
  tests/test_dataset.py
  tests/test_integration.py
  tests/test_zarr_checksum.py
Labels: feature

#136 fix: Issue where a None token breaks the login flow
  polaris/hub/external_auth_client.py
Labels: fix

#137 Only adding zarrRootPath field to datasets that use Zarr
  polaris/hub/client.py
Labels: fix

#141 Fix undefined split during checksum calc with multiple test sets
  polaris/benchmark/_base.py
Labels: fix

#140 Adding a loading indicator for upload/download operations
  env.yml
  polaris/hub/client.py
  polaris/utils/context.py
  pyproject.toml
Labels: feature

#135 Allow an empty train partition to support test-set only (e.g. zero-shot) benchmarks
  polaris/benchmark/_base.py
  tests/test_benchmark.py
Labels: feature

#146 Fix: `PolarisFileSystem` uses the dataset name instead of the dataset slug, causing a 404
  docs/tutorials/dataset_zarr.ipynb
  polaris/dataset/_dataset.py
  polaris/hub/polarisfs.py
Labels: fix

#148 optimizing time complexity of split field validator
  polaris/benchmark/_base.py
Labels: enhancement, feature

#144 Adding more informative error messaging due to potential JWT and Clerk data discrepancy
  polaris/benchmark/_base.py
  polaris/dataset/_dataset.py
  polaris/hub/client.py
  polaris/hub/polarisfs.py
  polaris/mixins/__init__.py
  polaris/mixins/_checksum.py
  polaris/mixins/_format_text.py
  polaris/utils/context.py
  polaris/utils/errors.py
Labels: documentation, chore

#155 Updating `base_request_to_hub` method to allow handling of responses without json
  polaris/hub/client.py
Labels: fix

#159 Updating dataset upload to respect `Dataset` name
  polaris/hub/client.py
Labels: fix

#158 Updating split validator to allow duplicates across test sets
  polaris/benchmark/_base.py
  tests/test_benchmark.py
Labels: fix

#165 Improving token errors and quickstart guide
  docs/quickstart.md
  polaris/hub/client.py
Labels: documentation, fix

#167 Adding correct name of package during version fetch
  polaris/_version.py
Labels: fix
