Repository polaris-hub/polaris, pull requests merged in 2024-11, with the labels that each got.

#215 Fix minor bug in docs rendering
  docs/quickstart.md
Labels: documentation

#216 fix: Allow extra settings in the .env file
  polaris/hub/settings.py
Labels: fix

#187 Chore: First class predictions
  docs/api/evaluation.md
  docs/tutorials/competition.participate.ipynb
  mkdocs.yml
  polaris/benchmark/__init__.py
  polaris/benchmark/_base.py
  polaris/evaluate/__init__.py
  polaris/evaluate/_metric.py
  polaris/evaluate/_predictions.py
  polaris/evaluate/_results.py
  polaris/evaluate/metrics/__init__.py
  polaris/evaluate/utils.py
  polaris/hub/client.py
  polaris/utils/misc.py
  polaris/utils/types.py
  tests/test_benchmark.py
  tests/test_benchmark_predictions.py
  tests/test_competition.py
Labels: chore

#219 Chore: Add `imagecodecs` as an optional dependency
  polaris/__init__.py
  polaris/dataset/_base.py
  polaris/dataset/zarr/_utils.py
  polaris/utils/errors.py
  pyproject.toml
  tests/conftest.py
  tests/test_benchmark.py
  tests/test_competition.py
  tests/test_dataset.py
  tests/test_dataset_v2.py
  tests/test_evaluate.py
  tests/test_factory.py
  tests/test_zarr_checksum.py
Labels: chore

#221 feat: Add an optional username/password login mode
  polaris/hub/client.py
  polaris/hub/settings.py
  polaris/hub/storage.py
Labels: feature
