Repository polaris-hub/polaris, pull requests merged in 2024-04, with the labels that each got.

#86 Updating column adapter logic and usage
  polaris/_artifact.py
  polaris/dataset/_adapters.py
  polaris/dataset/_dataset.py
  tests/conftest.py
  tests/test_evaluate.py
  tests/test_type_checks.py
Labels: fix

#88 Fix "Connection reset by peer" error when uploading large-ish Zarr datasets
  polaris/hub/polarisfs.py
Labels: fix

#94 Update issue templates
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/default-template.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: documentation

#92 feat: Copy a Zarr archive to the Hub using copy_store for increased efficient
  polaris/hub/client.py
  polaris/utils/types.py
Labels: feature
