Repository polaris-hub/polaris, pull requests merged in 2025-01, with the labels that each got.

#231 Feature: Client support for competitions
  .gitignore
  docs/api/competition.dataset.md
  docs/api/competition.evaluation.md
  docs/api/dataset.md
  docs/tutorials/competition.participate.ipynb
  env.yml
  mkdocs.yml
  polaris/__init__.py
  polaris/benchmark/_base.py
  polaris/benchmark/_split.py
  polaris/benchmark/_task.py
  polaris/competition/__init__.py
  polaris/competition/_competition.py
  polaris/dataset/__init__.py
  polaris/dataset/_base.py
  polaris/dataset/_competition_dataset.py
  polaris/dataset/_dataset.py
  polaris/dataset/_dataset_v2.py
  polaris/evaluate/__init__.py
  polaris/evaluate/_metadata.py
  polaris/evaluate/_predictions.py
  polaris/evaluate/_results.py
  polaris/experimental/_benchmark_v2.py
  polaris/experimental/_split_v2.py
  polaris/hub/client.py
  polaris/hub/storage.py
  polaris/loader/__init__.py
  polaris/loader/load.py
  polaris/utils/types.py
  pyproject.toml
  tests/conftest.py
  tests/test_benchmark.py
  tests/test_benchmark_v2.py
  tests/test_competition.py
  tests/test_dataset_v2.py
Labels: feature

#243 Add custom codecs for RDKit Molecules and Biotite AtomArrays
  polaris/__init__.py
  polaris/dataset/__init__.py
  polaris/dataset/zarr/codecs.py
  tests/test_codecs.py
Labels: feature

#244 chore: Improve data loading performance in S3 store
  polaris/dataset/_base.py
  polaris/dataset/_dataset_v2.py
  polaris/hub/storage.py
Labels: chore

#245 chore: Add a CI job to run tests in Conda, to detect dependency failure earlier
  .github/workflows/code-check.yml
  .github/workflows/doc.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .gitignore
  env.yml
  pyproject.toml
  uv.lock
Labels: chore

#247 fix: Pin Boto3 version to avoid breaking change
  env.yml
  pyproject.toml
  uv.lock
Labels: fix

#249 fix: Prevent external AWS configuration from breaking our boto3 config
  polaris/hub/storage.py
  uv.lock
Labels: fix

#250 fix: Replace yaspin with halo for spinners
  env.yml
  polaris/utils/context.py
  pyproject.toml
  uv.lock
Labels: fix

#252 fix: Better handling when no cached token exists, with more decriptive error
  polaris/cli.py
  polaris/hub/client.py
  polaris/hub/external_client.py
  polaris/loader/load.py
  polaris/utils/context.py
  pyproject.toml
  uv.lock
Labels: fix

#253 chore: Clean up error handling around Hub client requests
  docs/api/hub.polarisfs.md
  mkdocs.yml
  polaris/hub/client.py
  polaris/hub/polarisfs.py
  polaris/utils/errors.py
  pyproject.toml
  uv.lock
Labels: chore

#254 Chore: Remove duplicate and unused CompetitionPredictions class
  polaris/evaluate/_results.py
Labels: chore

#260 chore: Update skip condition for integration tests
  polaris/hub/settings.py
  tests/test_hub_integration.py
Labels: chore

#258 `Subset.as_dataframe()` hides targets instead of raising an error
  polaris/dataset/_subset.py
  tests/test_subset.py
Labels: feature
