Repository polaris-hub/polaris, pull requests merged in 2025-04, with the labels that each got.

#282 fix: Prevent missing FastPDB on Conda install
  env.yml
  pyproject.toml
  uv.lock
Labels: fix

#272 feat: Artifact Versioning
  docs/tutorials/create_a_benchmark.ipynb
  docs/tutorials/create_a_dataset.ipynb
  polaris/_artifact.py
  polaris/benchmark/_base.py
  polaris/dataset/_base.py
  polaris/dataset/_dataset.py
  polaris/dataset/_dataset_v2.py
  polaris/hub/client.py
  polaris/utils/misc.py
Labels: feature

#271 Client: Model artifact remaining changes
  docs/tutorials/create_a_dataset.ipynb
  docs/tutorials/create_a_model.ipynb
  polaris/dataset/_subset.py
  polaris/evaluate/_metadata.py
  polaris/hub/client.py
Labels: feature, fix

#284 feat: Model Versioning
  docs/tutorials/create_a_model.ipynb
  polaris/benchmark/_base.py
  polaris/dataset/_base.py
  polaris/hub/client.py
  polaris/model/__init__.py
Labels: feature
