Repository polaris-hub/polaris, pull requests merged in 2025-02, with the labels that each got.

#261 Fix: Always pass bytes in the RDKitMolCodec
  polaris/dataset/zarr/codecs.py
  tests/test_codecs.py
Labels: fix

#264 Fix: UnicodeEncodeError on Windows due to emoji use
  polaris/hub/external_client.py
Labels: fix

#267 Docs: Refactored the documentation and deprecation warnings
  docs/api/benchmark.md
  docs/api/dataset.md
  docs/images/zarr.png
  docs/index.md
  docs/quickstart.md
  docs/resources.md
  docs/tutorials/basics.ipynb
  docs/tutorials/competition.participate.ipynb
  docs/tutorials/create_a_benchmark.ipynb
  docs/tutorials/create_a_dataset.ipynb
  docs/tutorials/custom_dataset_benchmark.ipynb
  docs/tutorials/dataset_pdb.ipynb
  docs/tutorials/dataset_sdf.ipynb
  docs/tutorials/dataset_zarr.ipynb
  docs/tutorials/optimization.ipynb
  docs/tutorials/submit_to_benchmark.ipynb
  docs/tutorials/submit_to_competition.ipynb
  mkdocs.yml
  polaris/benchmark/__init__.py
  polaris/benchmark/_base.py
  polaris/benchmark/_benchmark_v2.py
  polaris/benchmark/_split_v2.py
  polaris/competition/__init__.py
  polaris/dataset/_base.py
  polaris/dataset/_column.py
  polaris/dataset/_dataset.py
  polaris/dataset/_factory.py
  polaris/dataset/converters/_pdb.py
  polaris/dataset/converters/_sdf.py
  polaris/dataset/converters/_zarr.py
  polaris/evaluate/_results.py
  polaris/hub/client.py
  polaris/loader/load.py
  pyproject.toml
  tests/test_benchmark_v2.py
Labels: documentation

#269 chore: Update numpy version restriction
  env.yml
  pyproject.toml
  uv.lock
Labels: chore
